import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const SITE_URL = "https://vishwasjha.com";
const projectId = process.env.SANITY_PROJECT_ID || process.env.VITE_SANITY_PROJECT_ID || "6osvtvxy";
const dataset = process.env.SANITY_DATASET || process.env.VITE_SANITY_DATASET || "production";
const query = `*[_type == "post" && defined(slug.current) && defined(publishedAt) && !(_id in path("drafts.**"))] | order(publishedAt desc){"slug": slug.current, _updatedAt}`;

const escapeXml = (value) =>
  String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");

const toLastMod = (date) => (date ? new Date(date).toISOString().slice(0, 10) : null);

async function getPublishedPosts() {
  const endpoint = new URL(`https://${projectId}.api.sanity.io/v2023-07-01/data/query/${dataset}`);
  endpoint.searchParams.set("query", query);

  const response = await fetch(endpoint, { headers: { Accept: "application/json" } });
  if (!response.ok) {
    throw new Error(`Sanity sitemap query failed: ${response.status} ${response.statusText}`);
  }

  const { result } = await response.json();
  return Array.isArray(result) ? result : [];
}

function sitemapEntry(path, lastmod) {
  const url = new URL(path, SITE_URL).toString();
  return [
    "  <url>",
    `    <loc>${escapeXml(url)}</loc>`,
    lastmod ? `    <lastmod>${lastmod}</lastmod>` : null,
    "  </url>",
  ]
    .filter(Boolean)
    .join("\n");
}

function redirectRule(path, status) {
  return `${path}  /index.html  ${status}`;
}

async function main() {
  const posts = await getPublishedPosts();
  const entries = [sitemapEntry("/"), sitemapEntry("/blog")];

  for (const post of posts) {
    entries.push(sitemapEntry(`/blog/${encodeURIComponent(post.slug)}`, toLastMod(post._updatedAt)));
  }

  const sitemap = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries.join("\n"),
    "</urlset>",
    "",
  ].join("\n");

  // Netlify evaluates redirects in order. Explicitly rewrite only the
  // published React routes, then return the same React 404 UI with a real
  // HTTP 404 for every other client-side path.
  const redirects = [
    "# Generated by scripts/generate-sitemap.mjs. Do not edit manually.",
    redirectRule("/blog", "200"),
    ...posts.map((post) => redirectRule(`/blog/${encodeURIComponent(post.slug)}`, "200")),
    redirectRule("/*", "404"),
    "",
  ].join("\n");

  const outputPath = resolve("public", "sitemap.xml");
  const redirectsOutputPath = resolve("public", "_redirects");
  await mkdir(dirname(outputPath), { recursive: true });
  await Promise.all([
    writeFile(outputPath, sitemap, "utf8"),
    writeFile(redirectsOutputPath, redirects, "utf8"),
  ]);
  console.log(`Generated sitemap.xml with ${entries.length} URLs and ${posts.length} blog route rewrites.`);
}

main().catch((error) => {
  console.error(error.message);
  process.exitCode = 1;
});
